### ISSUE TITLE
Conform to Spoon conventions

### ISSUE THREAD

**Issue by jokajak** [dbalatero/VimMode.spoon#10]
I was trying to use SpoonInstall to install this spoon from my fork where I've set up the repo to work with SpoonInstall. Unfortunately the code doesn't align with the conventions in https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md

Do you have any interest in a PR that aligns some of the code with the Spoon conventions?

**Comment by dbalatero** [comment]
@jokajak Hey! I do, but I am also in the middle of rewriting this spoon to handle way more Vim functionality, use easier to work with state machines, and make it test-driven. If you want to do it for the current `master` that's good too.

I will consult this markdown link you sent as I am developing v2 and make sure that SpoonInstall works correctly!

**Comment by dbalatero** [comment]
In #13 I went through the doc you linked and updated things. I will close this for now unless there is something key that I missed.

**Comment by dbalatero** [comment]
(this is in my rewrite branch however, but will get to `master` hopefully soon in the next 0-2 weeks!)
