### ISSUE TITLE
Implement `dd`

### ISSUE THREAD

**Issue by dbalatero** [dbalatero/VimMode.spoon#2]

**Comment by philc** [comment]
This would be very useful for deleting files in Finder.

**Comment by dbalatero** [comment]
@philc Sorry just catching up on this. I implemented `dd` to just work for text. It's hard to make context-specific functionality in Finder – we can detect for example that the focused window is called "Finder", but we don't know if we have a file selected or if we are focused in a text search box. Doing that context detection feels out of scope – I just use the default `cmd + delete` to delete a selected file and `cmd + shift + delete` for emptying the Trash.
