### ISSUE TITLE
attempt to index a nil value (field 'appWatcher')

### ISSUE THREAD

**Issue by ngriffin7a** [dbalatero/VimMode.spoon#36]
Hi, my Hammerspoon console is reporting the following error:

```2020-02-04 11:01:50: *** ERROR: .hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:112: attempt to index a nil value (field 'appWatcher')
stack traceback:
	.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:112: in function 'VimMode.disableForApp'
	/Users/ngriffin/.hammerspoon/init.lua:11: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)```

Would appreciate any insights anyone might have. Thanks!

**Comment by dbalatero** [comment]
@ngriffin7a hi - i've been trying to track this down as well. Question: does this happen on a laptop that goes to sleep/wakes a bunch?

**Comment by ngriffin7a** [comment]
Hi @dbalatero thanks so much for the quick response. The laptop is closed each night, and then reopened each morning.

**Comment by dbalatero** [comment]
As a quick test, if you restart Hammerspoon, close the lid, let it go
completely to sleep, wake it up, then switch between apps, do you see the
error in the logs?

**Comment by ngriffin7a** [comment]
@dbalatero Sorry for the delay in responding. Hammerspoon gives me the error under all circumstances:
1. When I cold start my laptop
2. When I restart hammerspoon
3. When I reload the hammerspoon config
4. When I close the laptop lid, let it go to sleep, open the lid, and reload the hammerspoon config

Have you made any progress in determining what might be the cause? Thanks!

**Comment by dbalatero** [comment]
I haven't yet… been in the middle of a cross-country move. I set this to
remind me in a week but if you are able to poke at it at all, please do!

**Comment by dbalatero** [comment]
@ngriffin7a I'm circling back on this. Would you mind giving me your config?

**Comment by dbalatero** [comment]
@andycmaj you also thumbs up'd this - do you have extra insights to share with me to help track this down?

**Comment by dbalatero** [comment]
I'm wondering if 99cb78f fixes it?

**Comment by ngriffin7a** [comment]
@dbalatero I applied your patch for ASDF locally to ~/.hammerspoon/Spoons/VimMode.spoon/lib/app_watcher.lua but now I get a different error:

```
2020-03-23 14:04:07: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-03-23 14:04:07: -- Lazy extension loading enabled
2020-03-23 14:04:07: -- Loading ~/.hammerspoon/init.lua
2020-03-23 14:04:07: -- Loading Spoon: VimMode
2020-03-23 14:04:07: -- Loading extension: inspect
2020-03-23 14:04:07: -- Loading extension: logger
2020-03-23 14:04:07: -- Loading extension: hotkey
2020-03-23 14:04:07: 14:04:07     hotkey: Enabled hotkey ESCAPE
2020-03-23 14:04:07: *** ERROR: ...s/ngriffin/.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:112: attempt to index a nil value (field 'appWatcher')
stack traceback:
	...s/ngriffin/.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:112: in function 'VimMode.disableForApp'
	/Users/ngriffin/.hammerspoon/init.lua:11: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Which config file did you want me to send?

**Comment by ngriffin7a** [comment]
@dbalatero I applied your patch for 99cb78fd11d3ac1975497766c8a25f5064785500 locally to ~/.hammerspoon/Spoons/VimMode.spoon/lib/app_watcher.lua but I get the same error.

Which config file did you want me to send?

**Comment by andycmaj** [comment]
@dbalatero this is silly, but i forgot to switch my local clone of your repo to `vim-mode-v2` before i enabled it in my spoon config 🤦‍♂ 

thanks for following up! and maybe it's as simple as that for others :)

**Comment by ngriffin7a** [comment]
I've been using the `vim-mode-v2` branch the whole time and still have the problem. I just rebased and the error is the same.

Here is the config file:

```
vim = hs.loadSpoon('VimMode')

-- Basic key binding to ctrl+;
-- You can choose any key binding you want here, see:
--   https://www.hammerspoon.org/docs/hs.hotkey.html#bind

hs.hotkey.bind({}, 'escape', function()
  vim:enter()
end)

vim:disableForApp('iTerm2')
vim:disableForApp('MacVim')
vim:disableForApp('Terminal')
```

**Comment by dbalatero** [comment]
@ngriffin7a Ugh, I think the documentation is broken between v1 and v2.

Can you replace `vim = hs.loadSpoon('VimMode')` with:

```lua
local VimMode = hs.loadSpoon('VimMode')
local vim = VimMode:new()
```

**Comment by ngriffin7a** [comment]
@dbalatero That fixed it, thanks!

**Comment by dbalatero** [comment]
Ok awesome, I will update the docs!
