### ISSUE TITLE
"Enter Normal Mode" Keybinding Disabled in "disableForApp"

### ISSUE THREAD

**Issue by olivertaylor** [dbalatero/VimMode.spoon#44]
I have `ctrl+[` set to enter VimMode's Normal mode, but have also set `vim:disableForApp('Emacs')`.

This seems to entirely disable the `ctrl+[` shortcut in Emacs.

I would expect that in disabled apps the shortcut would get passed through hammerspoon to the app, not simply absorbed by it.

(Also, amazing spoon! I LOVE it)

**Comment by dbalatero** [comment]
@olivertaylor Makes sense to me. If you want to fix it, the relevant code is here:

https://github.com/dbalatero/VimMode.spoon/blob/master/lib/vim.lua#L87-L89

We'd need to check for:

```
if self.disabled then
  -- pseudocode! have to look sending keys again
  sendKeys({'ctrl'}, '[')
end
```

I'll try to fix soon though!

**Comment by dbalatero** [comment]
@olivertaylor This is all good now, and I made the enable/disable functionality actually work without weird bugs. You can pull `master` and update the spoon!

**Comment by olivertaylor** [comment]
@dbalatero Awesome! Thank you.
