### ISSUE TITLE
enterWithSequence('jj') isn't working

### ISSUE THREAD

**Issue by assertcarlos** [dbalatero/VimMode.spoon#47]
I frequently use `jj` to enter normal and is a habit I can't get out of and `enterWithSequence` doesn't take me into normal mode.

Although `vim:bindHotKeys({ enter = {{'ctrl'}, ';'} })` works it feels awkward.

Not sure if it makes a difference but I am on Big Sur beta.

**Comment by dbalatero** [comment]
@assertcarlos As a quick test, does `jk` work for you? I want to see if it's the `jj` that's broken (I use `jk`)

**Comment by dbalatero** [comment]
(I will also see if I can repro it as well)

**Comment by dbalatero** [comment]
Ok yeah, it seems to be a `jj` (repeated single key) problem. I will debug and fix.

**Comment by dbalatero** [comment]
@assertcarlos ok, it should be in master and fixed! The issue was that the default key sequence timeout was too short, and `jj` is a less efficient keypair to type than `jk`, but I had set the timeout only testing with `jk`. `jj` needs an extra 40ms or so timeout, as it's always slower to repeat keys.

**Comment by dbalatero** [comment]
Also if the new default doesn't work for you, set a new one: `enterWithSequence('jj', 300)`

**Comment by assertcarlos** [comment]
Sorry I was doing a software update.

I've just updated and it is no working perfectly.

Thank you.

**Comment by dbalatero** [comment]
@assertcarlos Great! I merged another bug fix that's worth grabbing too if you don't have it.

**Comment by assertcarlos** [comment]
@dbalatero Thanks for the heads up! i'll get it now.
