### ISSUE TITLE
add operator 'x' to 'cut' or mod 'd' to place in register as 'y' copies

### ISSUE THREAD

**Issue by cometsong** [dbalatero/VimMode.spoon#5]
paste: https://github.com/dbalatero/VimMode.spoon/blob/master/init.lua#L284
delete: https://github.com/dbalatero/VimMode.spoon/blob/master/lib/operators.lua#L19

Add in `operators.cut` using `utils.sendKeys({'cmd'}, 'x')` cf. `operators.yank` does 'copy'.

**Comment by cometsong** [comment]
FYI: working on a pull-request now.

**Comment by dbalatero** [comment]
@cometsong Thanks for working on a PR! I think I already implemented the `x` key but it's totally possible I misunderstood its scope and what it should do (especially in visual vs normal mode).

**Comment by cometsong** [comment]
`x` is equivalent to 'cmd-x', the `d` is equivalent to 'delete'.  

In visual mode it cuts everything in the visual selection, whereas in normal the selection is the single character it is on top of.  Similar to `d` functionality, but cuts it to "clipboard" instead of deleting it.

Though Vim stores almost every thing it copies/cuts/delete in a `register` I can handle it if this spoon doesn't. 😉

**Comment by dbalatero** [comment]
@cometsong there is no register handling but there's no reason you couldn't add a hook for storing to a register as a separate pr.

**Comment by cometsong** [comment]
Having issues with this... the 'cut' method I've created works fine, when the `bind` method is to another character; it does *not* work when bound to 'x' or 'shift-x', etc.
Not sure if it's on my own box, or VimMode or Hammerspoon-related, or not. :(

Can I create the pull request and you can test it on your own setup to make sure it's not mac-related?

**Comment by cometsong** [comment]
My added method attempts pasted below, `cutNext` working when bound to non-x character (here 'z') and an attempt to mimic the previous 'x' map you had using the `compose` function to serialize.
```lua
  local cutNext = function()
    if not self.commandState.visualMode then
      utils.sendKeys({'shift'}, 'right')
      utils.sendKeys({'cmd'}, 'x')
    else
      utils.sendKeys({'cmd'}, 'x')
    end
  end

  local cut = compose(
    cutNext,
    self:exit()
  )
```
And the bindings:
```lua
  self.mode:bind({}, 'z', cutNext) -- works as expected using non-x char ?!
  --self.mode:bind({}, 'x', cutNext) -- only selects, not cuts
  --self.mode:bind({'shift'}, 'x', cutNext) -- only selects, not cuts
  --self.mode:bind({}, 'x', compose(cutNext, motions.right(self)))
  self.mode:bind({}, 'x', cut)
```

**Comment by dbalatero** [comment]
@cometsong can you open a pull request with a branch that I can checkout?

I'm happy to take a look at it later tonight. One thing that catches my eye:

```lua
  local cut = compose(
    cutNext,
    -- I think you should wrap this.
    function() self:exit() end
  )
```

`compose()` is expecting functions to be passed to it, and when you pass in `self:exit()` as an argument you're actually calling the exit function as you `compose` the command together. What you really want is something like this:

```lua
compose(cutNext, self:exit)
```

However, in my limited Lua experience I can't seem to pass object instance methods as function arguments, probably because the specific instance of the object they are bound to doesn't allow it to be passed around as a function arg. That's why I would say to wrap it w/ `compose(cutNext, function() self:exit() end)`

**Comment by cometsong** [comment]
OK i'll commit and put together a PR for this.
As a note, I added in the self:exit bit just to have more than one in the list.  I tried it without that as well.
