### ISSUE TITLE
Disable for Seal?

### ISSUE THREAD

**Issue by brandonxoliver** [dbalatero/VimMode.spoon#53]
Is it possible to disable normal mode when launching Hammerspoon Seal? I can disable for regular apps, but can't seem to work out how for Hammerspoon itself. Thanks!

**Comment by dbalatero** [comment]
@brandonxoliver I have no idea what that plugin is, so I think I need you to do a bit more digging on this one. Is there a way to detect whether Seal is being used?

What is the exact conflict you are having that leads you to want to disable it in Seal?

**Comment by dbalatero** [comment]
If Seal uses `hs.chooser`, which I think it does, you can do the following:

```lua
local vim = VimMode:new()

hs.chooser.globalCallback = function(chooser, eventName)
  hs.chooser._defaultGlobalCallback(chooser, eventName)

  if eventName == "willOpen" then
    vim:disable()
  else
    vim:enable()
  end
end
```

**Comment by dbalatero** [comment]
@brandonxoliver ping? does this work?

**Comment by dbalatero** [comment]
Closing due to no follow up.
