### ISSUE TITLE
Notification blocks text

### ISSUE THREAD

**Issue by Yemeen** [dbalatero/VimMode.spoon#54]
Last issue I swear! The notification for normal mode tends to block my text on the safari browser. I tried using the flux flicker option but it doesn't work when my own screen is already tinted. Would there be a way to make the notification stay in the bottom left kind of like vim? 
![Screen Shot 2020-09-06 at 9 11 46 PM](https://user-images.githubusercontent.com/11223834/92339869-33966680-f086-11ea-8d49-67601ea24037.png)

**Comment by dbalatero** [comment]
Weird, I see this on Safari (I am on Mojave):

![image](https://user-images.githubusercontent.com/59429/92340325-e3200880-f087-11ea-9f1e-688b3608977f.png)

What is your operating system/version? Are there other settings that would be different?

**Comment by Yemeen** [comment]
I'm on Catalina but I think the difference between our screenshots is that my safari was at the very top of my screen and so the notification was pushed down on to the bar unlike yours.

**Comment by dbalatero** [comment]
Got it! I know how to fix this one.

**Comment by dbalatero** [comment]
Now:
![image](https://user-images.githubusercontent.com/59429/92341185-e9fc4a80-f08a-11ea-944e-4cdfa9d25038.png)
