### ISSUE TITLE
Hitting g while in normal mode locks all key binds

### ISSUE THREAD

**Issue by Yemeen** [dbalatero/VimMode.spoon#56]
I'm not sure if the recent branch did this but just tapping g will now break all commands until normal mode is exited and restarted again. I couldn't get an error message for it except for when I do shift-g in messenger and then I get
```
22:08:30 ERROR:   LuaSkin: hs.hotkey callback: .../VimMode.spoon/lib/strategies/accessibility_strategy.lua:105: attempt to compare nil with number
stack traceback:
	.../VimMode.spoon/lib/strategies/accessibility_strategy.lua:105: in method 'fire'
	/Users/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:336: in function 'VimMode.fireCommandState'
	...rs/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/state.lua:58: in function <...rs/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/state.lua:57>
	(...tail calls...)
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:79: in upvalue 'transition'
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:74: in upvalue 'transition'
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:62: in upvalue 'transition'
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:87: in method 'fire'
	...rs/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/state.lua:55: in function <...rs/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/state.lua:53>
	(...tail calls...)
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:79: in upvalue 'transition'
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:74: in upvalue 'transition'
	...merspoon/Spoons/VimMode.spoon/lib/utils/statemachine.lua:62: in method 'enterMotion'
	/Users/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:160: in function 'VimMode.enterMotion'
	...rs/yayub/.hammerspoon/Spoons/VimMode.spoon/lib/modal.lua:34: in local 'handler'
	...ammerspoon/Spoons/VimMode.spoon/lib/contextual_modal.lua:56: in function <...ammerspoon/Spoons/VimMode.spoon/lib/contextual_modal.lua:46>
```

Thank you!

**Comment by dbalatero** [comment]
Well that's annoying haha. 

This is happening because I guess I bound `gg` to go to the top of a document:

https://github.com/dbalatero/VimMode.spoon/blob/677d665b7ff0fd18f321792edaf28505d4faece8/lib/modal.lua#L166-L170

And the only thing you can do in that mode is tap `g` a second time, or `esc` to exit normal mode. Hmm. It should probably indicate that you tapped a `g` or something, like when you hit `f` and a `[f]` appears in the box.

I wonder what to do here. A lot of plugins in Vim bind themselves to `g` plus a letter, e.g. `gd` jumps to definition in coc.nvim for me.

Should hitting any other key besides `g` just reset the normal mode state and let you enter in another command?

**Comment by Yemeen** [comment]
I always assumed gg needed to be hit rapidly in vim or else it wouldn't work but apparently not! It seems that vim resets the normal mode if you do g followed by a command it doesn't know. Are there other commands that this might affect also?

**Comment by dbalatero** [comment]
Ok so I think the thing to do here is:

* Show a `[g]` indicator when you tap `g`
* I think `esc` should probably just clear the `g` and not take you _out_ of normal mode
* Probably tapping all other keys as a catch all should just go back to normal mode as well

> Are there other commands that this might affect also?

What do you mean? I don't think so?

**Comment by Yemeen** [comment]
I meant if you had any other 2+ letter commands that this might affect but looking at the file you referenced earlier that doesn't seem to be the case.

**Comment by normen** [comment]
I'd also say that when pressing any "unknown" key after the "g" it should reset to normal mode, just like VIM does. The other thing is displaying an indicator for already pressed keys, just like VIM and most other VIM emulations do - as you said.

**Comment by dbalatero** [comment]
> I'd also say that when pressing any "unknown" key after the "g" it should reset to normal mode, just like VIM does.

I'd really like this behavior as well - unfortunately the `hs.modal` bind system I'm using doesn't really let you disable all other keys. Overhauling the modal system in general is something I'd like to do, as I'm already extending it to allow for "sub-menus" (context).

**Comment by dbalatero** [comment]
@normen @Yemeen Sorry for the delay on this one. I've fixed the indicator, and escape should work out of the `g` context and reset to normal mode.

> Probably tapping all other keys as a catch all should just go back to normal mode as well

This is going to take more work, so I'm going to punt until later.
