### ISSUE TITLE
Fails after install

### ISSUE THREAD

**Issue by jonasdiemer** [dbalatero/VimMode.spoon#59]
Hi,

just wanted to try VimMode out, but it failed after install with the following messages in the Hammerspoon console:

> 2020-10-05 10:29:38: Welcome to the Hammerspoon Console!
> You can run any Lua code in here.
> 
> 2020-10-05 10:29:38: -- Lazy extension loading enabled
> 2020-10-05 10:29:38: -- Loading ~/.hammerspoon/init.lua
> 2020-10-05 10:29:38: -- Loading Spoon: SpoonInstall
> 2020-10-05 10:29:38: *** ERROR: Unable to load Spoon: SpoonInstall
> 2020-10-05 10:29:38: -- Loading Spoon: VimMode
> 2020-10-05 10:29:38: -- Loading extension: inspect
> 2020-10-05 10:29:38: -- Loading extension: logger
> 2020-10-05 10:29:38: *** ERROR: error loading module 'hs._asm.axuielement.internal' from file '/Users/jdiemer/.hammerspoon/Spoons/VimMode.spoon/vendor/hs/_asm/axuielement/internal.so':
> 	dlopen(/Users/jdiemer/.hammerspoon/Spoons/VimMode.spoon/vendor/hs/_asm/axuielement/internal.so, 6): Symbol not found: _lua_newuserdata
>   Referenced from: /Users/jdiemer/.hammerspoon/Spoons/VimMode.spoon/vendor/hs/_asm/axuielement/internal.so
>   Expected in: /Applications/Hammerspoon.app/Contents/MacOS/../Frameworks/LuaSkin.framework/Versions/A/LuaSkin
>  in /Users/jdiemer/.hammerspoon/Spoons/VimMode.spoon/vendor/hs/_asm/axuielement/internal.so
> stack traceback:
> 	[C]: in ?
> 	[C]: in function 'rawrequire'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
> 	...Spoons/VimMode.spoon/vendor/hs/_asm/axuielement/init.lua:27: in main chunk
> 	[C]: in function 'rawrequire'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
> 	...rs/jdiemer/.hammerspoon/Spoons/VimMode.spoon/lib/vim.lua:18: in main chunk
> 	[C]: in function 'dofile'
> 	/Users/jdiemer/.hammerspoon/Spoons/VimMode.spoon/init.lua:10: in main chunk
> 	[C]: in function 'rawrequire'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:651: in function 'require'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:324: in field 'loadSpoon'
> 	/Users/jdiemer/.hammerspoon/init.lua:6: in main chunk
> 	[C]: in function 'xpcall'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
> 	(...tail calls...)

**Comment by dbalatero** [comment]
Yes, Hammerspoon broke things by forcing a different Lua version in 0.9.79.

See issue #58.

I haven't fixed it yet, but I will soon as I am held back from upgrading as well. If you want to try it out for now, get a release version of 0.9.78 and I will try to fix this week.

**Comment by jonasdiemer** [comment]
Thanks for your response. I tried 0.9.79, same issue. 0.9.78 worked (after manually downloading and installing SpoonInstall).

Looking forward to a fix.
