### ISSUE TITLE
Pressing j in normal mode results in typing the letter j 

### ISSUE THREAD

**Issue by peelin** [dbalatero/VimMode.spoon#61]
Hi,

I followed the instructions on the readme to set it so that pressing 'jk' enters vim mode.

This works fine, I can press 'jk' to enter vim mode and use the commands, and also hkl for navigating.
However when I press j, the letter j appears instead of moving the cursor down.

Interestingly if I press 'jk' again, while already in vim mode, then the j command works properly.

Any ideas what could be causing this?

![vimmode](https://user-images.githubusercontent.com/20291657/96804965-74e89880-13de-11eb-9288-666afa5dea47.gif)

**Comment by dbalatero** [comment]
Hey @peelin,

I have no idea. It works for me currently. The latest Hammerspoon updates have kind of created minor breakages across many of my configs, but that's kind of a cop out answer.

Potential ways out of this:

* open the Hammerspoon console and see if any salient errors are printing out there that might be interesting
* start logging things to the console on your end, if you have the appetite
* I screenshare with you and you give me control of your computer, and I'll start logging things and poking around

Beyond that this is kind of hard to debug just staring at this gif, so I need more to go on at this point…

Also what version of HS are you running?

**Comment by dbalatero** [comment]
Also do you have any personal key binds or modals in your own config that could be conflicting somehow?

**Comment by peelin** [comment]
I was using hammerspoon 0.9.78 because of #58 , but I just noticed you pushed an update for 0.9.81 so I upgraded. The issue persists. To answer some of your questions,

*  vimspoon is the only thing I'm using with hammerspoon.
* there are no error messages in the hammerspoon console.

I'll do a fresh install on a new account later  and let you know how it goes.

**Comment by peelin** [comment]
Alright, I finally got around to re-installing hammerspoon and vimspoon and everything works fine now. 
I think I tried to reinstalling before, but didn't delete ~/.hammerspoon and so it didn't fix the issue.
Thanks!

**Comment by dbalatero** [comment]
Glad to hear it! And sorry to hear the versioning is so fragile. Wish I knew what caused the little differences that forced you to reinstall…
