### ISSUE TITLE
function for enableForApp

### ISSUE THREAD

**Issue by joe-zhang3** [dbalatero/VimMode.spoon#70]
This should not be an issue. I am vim-user, I only want to use vim for input fields of browsers like Chrome. So I am wondering if it is possible to have a function enableForApp that I can specify which app that I want VimMode to take effect? 

There are so many apps that I already have vim configured, so I don't want to use `disableForApp` to exclude them one by one.

Apprecaited.

**Comment by bion** [comment]
> This should not be an issue.

I'm not the maintainer, but if I were I'd reject your feature request after reading the first sentence for being rude and demanding. If you want make a pull request.

**Comment by dbalatero** [comment]
> This should not be an issue.

It's not really a high priority for me, just so you're aware.

> There are so many apps that I already have vim configured

Can you help me understand the total number of apps you have some kind of Vim mode configured in? 5? 10? 20? 100? Ballpark is OK.

It's hard for me to imagine that the number would be super high but I'm curious to be proven wrong.

**Comment by joe-zhang3** [comment]
@dbalatero , you are right, it is not that many, just iTerm, Rider, Idea, PyCharm, Atom, Sublime, VSCode, azure data studio etc. I also have Vimium plugin for Chrome installed. 

The point is, ideally I just want VimMode to be enabled for address bar of Chrome. I am ok with the entire Chrome also, like any input fields of any pages. That means, it is easier to have `enableForApp` rather than `disableForApp` to exclude apps for my case. 

thanks,

**Comment by dbalatero** [comment]
I'd merge a reasonable PR if you sent one in, but this feels out of scope for me personally. I'm not really looking to support the "Vim user that uses 7 text editors with Vim plugins" use case. Whatever solution you came up with would need to play nice with `disableForApp`, so I'd recommend discussing your approach here before doing any coding.

**Comment by dbalatero** [comment]
> The point is, ideally I just want VimMode to be enabled for address bar of Chrome.

Also this isn't going to really happen.

**Comment by dbalatero** [comment]
Closing this issue but feel free to reopen if you want to make a patch!
