### ISSUE TITLE
Help disable for VirtualboxVM

### ISSUE THREAD

**Issue by molleweide** [dbalatero/VimMode.spoon#76]
Hi Dave,

        I am trying to disable VimSpoon when using
        Virtualbox for testing my configs and such
        on linux. 

        I disable Virtualbox as shown below.
        This is not working for me. I wantedt ask you
        if you have tried this before or if you have any
        other suggestion on what to do maybe?
        
        I will get back if I solve it myself!

        ```lua
        -- taken from hammerspoon/init.lua
        ..
        ...
        :disableForApp('iTerm2')
        :disableForApp('VirtualBoxVM')
        :disableForApp('zoom.us')
        ```

Thanks

**Comment by dbalatero** [comment]
Make sure `VirtualBoxVM` is the correct name? Dump the application name and bundle ID maybe to the Hammerspoon console:

https://www.hammerspoon.org/docs/hs.application.html#name

**Comment by molleweide** [comment]
Ohh good i have to try that i didnt think bout it first. Brb!!

**Comment by molleweide** [comment]
yo! this did it! 
`  :disableForApp('VirtualBox VM')`
