### ISSUE TITLE
"a" in normal mode types "a" instead of back to insert mode

### ISSUE THREAD

**Issue by albert-ying** [dbalatero/VimMode.spoon#79]
Hi, thank you for this awesome work! It is a bit unnatural for me that "a" in normal mode types literal "a" instead of back to insert mode. I'm wondering is it a bug or an unimplemented feature? If it is the latter, it shouldn't be hard as it is just equivalent to `right arrow + i` or `l + i`

**Comment by dbalatero** [comment]
Added it!
