### ISSUE TITLE
Extract enterWithSequence functionality

### ISSUE THREAD

**Issue by reawakening** [dbalatero/VimMode.spoon#81]
Thank you for this I was using it for Xcode and now they have finally released native vim support with Xcode 13 beta.

They don't have anyway of exiting insert mode with jk and It has become muscle memory for me.

I'm not familiar with Lua or writing my own Hammerspoon configuration and would love to be able to use your jk sequence functionality to trigger escape.

Could you point me in the right direction on how I could extract it.

Thank you 🙂

**Comment by dbalatero** [comment]
@reawakening Sorry for the delay.

You can copy this entire file:
https://github.com/dbalatero/VimMode.spoon/blob/48f01eec5bf7ac4e494efe8b92281827251c510b/lib/key_sequence.lua#L1-L142

Usage is:

```lua
local function onSequencePressed()
  -- do something
end

sequence = KeySequence:new('jk', nil, onSequencePressed)
sequence:enable()
```

Beyond that I can't help you with Lua or basic familiarity! You'll need to figure out what file to put it in, how to `require` it, etc.
