### ISSUE TITLE
Stay in vim mode until pressing esc

### ISSUE THREAD

**Issue by samplesizeofone** [dbalatero/VimMode.spoon#9]
Hi. Once VimMode is active, I'd like to use esc to return to normal mode if possible.

For example, press ctrl-; to activate VimMode. Then when I press i go to insert mode. But then pressing esc puts me back in normal mode instead of having to press ctrl-; again. Perhaps esc esc or ctrl-; could exit VimMode.

**Comment by samplesizeofone** [comment]
Love VimMode by the by :-)

**Comment by dbalatero** [comment]
@samplesizeofone Hi! I see the OS system default is "insert mode". Hitting `ctrl ;` or whatever you bind to `vim:enter()` will put you in normal mode. Hitting `i` exits you back to insert mode, the normal OS X experience. Does this help:?
