### ISSUE TITLE
Install via brew

### ISSUE THREAD

**Issue by LawranceFung** [dbalatero/VimMode.spoon#90]
Are there plans to support installing VimMode.spoon via brew?

**Comment by dbalatero** [comment]
What do you see as the benefits? There is a 1-liner install command already.

**Comment by LawranceFung** [comment]
Some people have a strong preference for installing through brew.  That also synergizes with automatically updating through brew, though that feature might be a bug for software that keybinds.  
I personally don't care, though brew is supported by many applications that are standard or popular.

**Comment by dbalatero** [comment]
Given this is a module of code that lives within Hammerspoon, it feels funny to install it via brew. I think for now I will not do this, as it's not something I feel strongly needs to happen and it would probably add more maintenance work to keep brew in sync.
